### ISSUE TITLE
Support Slack Threads

### ISSUE THREAD

**Issue by bradleyfalzon** [gopheracademy/gopher#15]
In some cases gopher responds to a threaded discussion by commenting in the room/channel, not the thread (where the trigger came from).

For example: 

![screenshot 2017-03-25 18 53 01](https://cloud.githubusercontent.com/assets/1834577/24320800/95fbd260-118c-11e7-9514-2e1a71202021.png)

Instead gopher should respond to the thread.

**Comment by dlsniper** [comment]
I think it's fixed now. Merry Christmas Everyone!
