### ISSUE TITLE
goher code linking should be updated

### ISSUE THREAD

**Issue by cyberhck** [gopheracademy/gopher#23]
if I send a message containing code, it creates a go playground link, but imaging if I sent only this in a message:
```go
package main

import (
	"encoding/json"
	"log"
	"os"
)

func getCodes(filename string) []SomeName {
	zcodes := make([]SomeName, 0)
	file, err := os.Open(filename)
	if err != nil {
		log.Fatal(err)
	}
	err = json.NewDecoder(file).Decode(&zcodes)
	if err != nil {
		log.Fatal(err)
	}
	return zcodes
}
func main() {
	getCodes("a-name.out")
}
```
it creates link like: https://play.golang.org/p/ItueVksYOs9

Notice, there's still ``` in the source code, this needs to be improved, and only the code should be present inside the editor :slightly_smiling_face:

**Comment by dlsniper** [comment]
The gopher doesn't bother detecting the content because people don't bother respecting others and paste huge amounts of text in chat. As such, while detection would be desirable, the least gopher can do now us iritate back people that post walls of text.

Sorry, but this won't be fixed.
