### ISSUE TITLE
link to playground should show preview

### ISSUE THREAD

**Issue by cyberhck** [gopheracademy/gopher#24]
If someone posts a link to golang playground, we should comment with the body of the message for easy access for everyone, even though everyone can run it in browser, maybe this can be done if it's less than N lines or something, and it can be collapsed by default if it's longer, or maybe don't do at all if it's long?

**Comment by dlsniper** [comment]
The purpose of gopher sending the code to playground is to make it easier to share / collaborate. This would be the reverse of it. Sorry but this won't be fixed
