### ISSUE TITLE
Add functionality for archiving a chain of messages. 

### ISSUE THREAD

**Issue by DameonSmith** [gopheracademy/gopher#29]
The idea is to enable the ability to select a section of messages to be archived. As it stands right now much of the knowledge shared and discovered in the slack is very easy to lose. It would be useful to the community to be able to take a chain of messages, archive them off 'somewhere', and then have them be searchable by topic. 

Some ideas that have been discussed would be to link to two messages and have gopher take and archive all messages between the two. Another idea that was proposed would be to implement archival of message threads, though there are some problems like file attachments and moderation that make this a challenging solution.

**Comment by dlsniper** [comment]
This would break Slack's ToS and we won't support it.

**Comment by dlsniper** [comment]
Not to mention the while GDPR issues we'd expose to.
