### ISSUE TITLE
Proposal: Add book command feature

### ISSUE THREAD

**Issue by ghost** [gopheracademy/gopher#35]
### Feature Proposal
The #golang-newbies channel posted this recently:

![gopher_feature](https://user-images.githubusercontent.com/12717226/41940779-e832bd5c-7967-11e8-8f16-1bbf905aef2a.jpg)

#### Current Behavior
@gopher books
:question:

#### Proposed Behavior
``@gopher books``
``Gopher App - {list of recommended books}``

Proposed initial Books list:
- Go In Action: William Kennedy, Brian Ketelsen, Erik St. Martin
- The Go Programming Language: Alan A A Donovan, Brian W Kernighan
- Go Programming Blueprints: Mat Ryer

#### Possible Solution
``bot.go:247``
Add proposed books list to the botEventTextToResponse map under the books key in the same format as recommended blogs is formatted

I'd be more than happy to submit this as a cr with the above implementation

**Comment by stuartellis** [comment]
Just a +1 to the proposed list of books.

**Comment by spiffcs** [comment]
Submitted here:

https://github.com/gopheracademy/gopher/pull/36
