### ISSUE TITLE
breaking changes to cloud.google.com/go/datastore

### ISSUE THREAD

**Issue by jba** [gopheracademy/gopher#9]
See https://groups.google.com/forum/#!topic/google-api-go-announce/hqXtM_4Ix-0 and https://groups.google.com/forum/#!topic/google-api-go-announce/79jtrdeuJAg.

**Comment by dlsniper** [comment]
@jba thank you so much for this, I'll keep an eye on it.

**Comment by jba** [comment]
You can probably make all the changes today, but the actual breakage is happening tomorrow.

**Comment by dlsniper** [comment]
Thanks. Is there a feed for this to keep an eye on? Or the mailing list is the best place to have a digest of it?

**Comment by jba** [comment]
You should subscribe to the announcement list I linked to.

**Comment by dlsniper** [comment]
Fixed in 46645c8f322426b5e7154dc7d21521df90e4439e
